# This is a template for Streamlit Cloud secrets
# Copy this content to your Streamlit Cloud app's secrets section

[api_keys]
google_api_key = "your_google_gemini_api_key_here"

# Note: Database configuration is not needed for this deployment
# as we're using SQLite which is file-based